### ISSUE TITLE
Rebar.ByCurve typecasting error 'Autodesk.DesignScript.Geometry.Geometry[]' to type 'Autodesk.Revit.DB.Curve'.

### ISSUE THREAD

**Issue by gaborschnierer** [tt-acm/DynamoForRebar#79] opened 2018-08-09 18:37 UTC
hi again moethu

I hope you don't mind the new issue, maybe its just a quick fix as last time. I'm clueless, because previous versions of Revit (2018) / Dynamo (1.x.x) / DynamoForRebar package had no problem to cast the DS curves into Revit.DB.Curve. And why is the Rebar.ByCurve identifying the input as .Geometry[]? Flattening the list or feeding single curves give the same error.

Warning: Rebar.ByCurve operation falied.
Unable to cast object of type
'Autodesk.DesignScript.Geometry.Geometry[]'
to type 'Autodesk.Revit.DB.Curve'.

![image](https://user-images.githubusercontent.com/30599750/43917459-b41b68c2-9c10-11e8-90b3-5688b892e207.png)

**Comment by moethu** [comment] 2018-08-12 15:11
thanks for reporting it, the issue is I don't have Revti2019 but I'll organize it

**Comment by moethu** [comment] 2018-08-14 06:48
Fixed with latest bin in repo, please download it and overwrite.

**Closed by moethu** 2018-08-14 06:48 UTC
Labels: bug
