### ISSUE TITLE
Wish: Creating Rebar Sets with Dynamo for Rebar

### ISSUE THREAD

**Issue by vasshaug** [tt-acm/DynamoForRebar#80] opened 2018-08-22 13:50 UTC
Is it possible to add a node that creates Rebar Sets in Revit to Dynamo for Rebar?
Potential use case is automating the creation and documentation of simple rebar layouts. Single Bars don't host information about Spacing, and Containers dont even have Rebar Number available.

**Comment by moethu** [comment] 2018-08-24 06:46
@vasshaug good point, I had a brief look but didn't find anything in the Revit API on RebarSets.

**Comment by eibre** [comment] 2018-08-24 08:16
@moethu Like in the GUI, you need to change the layout rule after a rebar is created.
![image](https://user-images.githubusercontent.com/5968613/44573372-ba6d9480-a786-11e8-8936-9d977908ff83.png)

http://www.revitapidocs.com/2018.1/587885c9-3090-c627-af6f-c72179ef49d1.htm

**Comment by moethu** [comment] 2018-08-24 11:33
Thanks for clarifying - I thought rebar sets would be some sort of container. So you'd like to use all SetLayout methods in Dynamo right?

**Comment by eibre** [comment] 2018-08-24 11:43
Yes, but I would say that `SetLayoutAsMaximumSpacing` would be the most used method. `SetLayoutAsMinimumSpacing` is in the opposite end (I've never used it personally)

**Comment by vasshaug** [comment] 2018-08-24 12:31
I've only ever used `SetLayoutAsMaximumSpacing` and `SetLayoutAsFixedNumber`

**Comment by moethu** [comment] 2018-08-24 15:51
Guys, please download and replace DynamoRebar.dll from this repo and let me know if this works for you.

**Comment by eibre** [comment] 2018-08-24 18:05
I added a couple of comments here: https://github.com/tt-acm/DynamoForRebar/commit/8ba35f56bd4646f97e18bea5de2d0a214d865972

By the way, this issue is a duplicate of https://github.com/tt-acm/DynamoForRebar/issues/73

**Comment by vasshaug** [comment] 2018-08-28 14:51
Did a quick test on Revit 2018.3 and Dynamo 2.0.1 and it seems to place rebar sets but there are two issues I'm seeing:
1. Units for "spacing" and "arrayLength"are hard coded to feet/inches. Can we use document units?
2. "Rebar.SetLayoutAsMaximumSpacing" returns nulls while still placing rebar sets. This prevents downstream usage, like "Rebar.SetSolidInView".

![image](https://user-images.githubusercontent.com/5300197/44731035-97264a80-aae2-11e8-94d3-86375f584ed1.png)

**Comment by moethu** [comment] 2018-08-29 07:58
@vasshaug thanks, I implemented your issues - returning an element + autoconvert units. please test and let me know if you are missing some things.

**Comment by moethu** [comment] 2018-09-02 14:47
i'll close this for now and release the update

**Closed by moethu** 2018-09-02 14:47 UTC
Labels: enhancement, in Progress
